# ALM Team Azure example pipeline that pulls in the maven build template from the devops_pipelines repository
# Copy this file to your repository and fill in the required parameters, AppName and Portfolio
# Commit the changes and trigger a new build

trigger:
  - master

# Repo: devops_pipelines/templates
# File: azure-pipelines.yml
resources:
  repositories:
    - repository: almtemplates
      type: git
      name: ALM/devops_pipelines


stages:
  - stage: Build
    jobs:
      - template: templates/java-mvn-build.yml@almtemplates
        parameters:
          AppName: "spring-boot-demo"
          Portfolio: "ESM"
