trigger:
  - master
  - develop

resources:
  repositories:
    - repository: almtemplates
      type: git
      name: ALM/devops_pipelines
    - repository: stacktemplates
      type: git
      name: Stack Team/devops_pipelines.robert.thornton


stages:
  - stage: Build
    jobs:
      - template: templates/java-mvn-build.yml@stacktemplates
        parameters:
          AppName: spring-boot-demo
          Portfolio: ESM
          JavaVersion: 11
          MavenPomFile: pom.kts
          MavenPomPath: .
          MavenGoal: clean verify
          RunMavenSonarScan: true
          DownloadSecureFile: false
          RunArtifactoryUpload: true
